"use client";
import { ArrowRight, CheckCircle2, Star } from "lucide-react";
import { trackEvent } from "@/lib/analytics";
import { EXPEDIA_GENERAL_AFFILIATE_URL } from "@/lib/revenuePartners";
const rel = "nofollow sponsored noopener noreferrer";
const send = (action: string, params: Record<string, string | number>) => trackEvent({ action, category: "conversion", params });
export function ConversionScrollAnalytics() { return null; }
export function ComparisonCard() { const click = () => { const p = { component_type: "ComparisonCard", placement: "conversion_section", page: location.pathname, partner: "expedia", page_path: location.pathname, outbound_url: EXPEDIA_GENERAL_AFFILIATE_URL }; send("comparison_click", p); send("comparison_page_click", p); send("affiliate_click", p); send("affiliate_cta_click", p); }; return <article className="rounded-3xl border border-slate-200 bg-white p-6 shadow-card"><p className="text-xs font-black uppercase tracking-[0.16em] text-ocean">Search vs booking</p><h2 className="mt-2 text-2xl font-black text-ink">Google Flights vs Expedia</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><div className="rounded-2xl bg-sand p-4"><h3 className="font-black text-ink">Google Flights</h3><p className="mt-2 flex gap-2 text-sm font-semibold text-slateText"><CheckCircle2 className="h-5 w-5 text-ocean" />Strong for flexible-date flight searches.</p></div><div className="rounded-2xl bg-sand p-4"><h3 className="font-black text-ink">Expedia</h3><p className="mt-2 flex gap-2 text-sm font-semibold text-slateText"><CheckCircle2 className="h-5 w-5 text-ocean" />Useful for booking and comparing flight + hotel options.</p></div></div><a className="mt-6 inline-flex h-12 items-center justify-center gap-2 rounded-xl bg-ocean px-6 text-sm font-black text-white" href={EXPEDIA_GENERAL_AFFILIATE_URL} target="_blank" rel={rel} onClick={click}>Compare Options <ArrowRight className="h-4 w-4" /></a></article>; }
export function RecommendedPartnerCard() { const click = () => { const p = { component_type: "RecommendedPartnerCard", placement: "conversion_section", page: location.pathname, partner: "expedia", page_path: location.pathname, outbound_url: EXPEDIA_GENERAL_AFFILIATE_URL }; send("partner_card_click", p); send("affiliate_click", p); send("affiliate_cta_click", p); }; return <article className="rounded-3xl border border-sky-200 bg-ink p-6 text-white shadow-premium"><Star className="h-7 w-7 text-gold" /><p className="mt-4 text-xs font-black uppercase tracking-[0.16em] text-sky-200">Recommended booking partner</p><h2 className="mt-2 text-2xl font-black">Expedia</h2><p className="mt-3 text-sm font-semibold leading-6 text-white/75">After finding useful dates and routes, compare booking and package options for the complete Florida trip.</p><a className="mt-6 inline-flex h-12 items-center justify-center gap-2 rounded-xl bg-white px-6 text-sm font-black text-ink" href={EXPEDIA_GENERAL_AFFILIATE_URL} target="_blank" rel={rel} onClick={click}>View Current Deals <ArrowRight className="h-4 w-4" /></a><p className="mt-3 text-xs font-bold text-white/60">Affiliate link. We may earn a commission at no extra cost to you.</p></article>; }
